import{a as M,S as P,i as j}from"./assets/vendor-BSTwZ_tR.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const B="https://corsproxy.io/?url=",T="https://pixabay.com/api",E="52704159-1137319808f91d343a45c96fe",R="photo",x="horizontal",A=!0,h=9,C={method:"GET",headers:{Accept:"application/json","Content-Type":"application/json"}};async function g(a,t){try{const o=`${T}/?key=${E}&q=${a}&image_type=${R}&orientation=${x}&safesearch=${A}&page=${t}&per_page=${h}`,s=await M(`${B}${o}`,C);if(!s.data)throw new Error(`HTTP error! Status: ${s.status}`);return s.data}catch(o){throw console.error(o),o}}const w=document.querySelector("ul.gallery"),b=document.querySelector(".loader"),L=document.querySelector(".load-more-btn"),O=new P(".gallery li a",{captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",nav:!0,captionDelay:250});function f(a){const t=a.map(({largeImageURL:o,webformatURL:s,tags:e,likes:r,views:c,comments:$,downloads:v})=>`<li class="gallery-item js-gallery-item">
                <a class="gallery-link" href="${o}">
                  <img class="gallery-image" src="${s}" width='100px' alt="${e.split(",").slice(0,3).join(",")}">
                  <ul class="image-params">
                    <li><b>Likes</b>:<br> ${r}</li>
                    <li><b>Views</b>:<br> ${c}</li>
                    <li><b>Comments</b>:<br> ${$}</li>
                    <li><b>Downloads</b>:<br> ${v}</li>
                  </ul>
                </a>
              </li>`).join("");w.insertAdjacentHTML("beforeend",t),O.refresh()}function D(){w.innerHTML=""}function q(){b.classList.add("is-shown")}function n(){b.classList.remove("is-shown")}function S(){L.classList.add("is-shown")}function p(){L.classList.remove("is-shown")}let i=1,u=0;const l={query:document.querySelector(".js-input-field"),form:document.querySelector(".js-form"),loadMoreButton:document.querySelector(".js-load-more-btn"),gallery:document.querySelector(".js-gallery")},m={emptyResponseMessage:"Sorry, there are no images matching your search query. Please try again!",emptyQueryMessage:"Please enter your search query image",endSearchResults:"We're sorry, but you've reached the end of search results."};let d="";function y(a){j.show({message:a,messageColor:"#ffffff",backgroundColor:"#fe5549",progressBar:!1,position:"center",timeout:1e4})}l.form.addEventListener("submit",async a=>{if(a.preventDefault(),i=1,d="",p(),D(),q(),await new Promise(requestAnimationFrame),l.query.value.trim()===""){n(),y(m.emptyQueryMessage);return}try{d=l.query.value.trim();const t=await g(d,i);if(u=Math.ceil(t.totalHits/h),!t.hits||t.hits.length===0){n(),y(m.emptyResponseMessage);return}if(i>=u){f(t.hits),n(),y(m.endSearchResults);return}f(t.hits),n(),i<u?S():p()}catch(t){console.log(t)}finally{n()}});l.loadMoreButton.addEventListener("click",async a=>{a.preventDefault(),i+=1;try{const t=l.gallery.children.length;p(),q(),await new Promise(requestAnimationFrame);const o=await g(d,i);if(i>=u){await new Promise(requestAnimationFrame),f(o.hits),n(),y(m.endSearchResults);return}f(o.hits),n(),i<u?S():p();const s=l.gallery.children[t];if(s){const e=s.getBoundingClientRect();console.log(e),window.scrollBy({top:e.height*2,behavior:"smooth"})}}catch(t){console.log(t)}finally{n()}});
//# sourceMappingURL=index.js.map
