import{a as $,S,i as q}from"./assets/vendor-BSTwZ_tR.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const v="https://corsproxy.io/?url=",M="https://pixabay.com/api",E="52704159-1137319808f91d343a45c96fe",P="photo",T="horizontal",x=!0,B=15,O={method:"GET",headers:{Accept:"application/json","Content-Type":"application/json"}};async function p(s,t){try{const r=`${M}/?key=${E}&q=${s}&image_type=${P}&orientation=${T}&safesearch=${x}&page=${t}&per_page=${B}`,a=await $(`${v}${r}`,O);if(!a.data)throw new Error(`HTTP error! Status: ${a.status}`);return a.data}catch(r){throw console.error(r),r}}const l=document.querySelector("ul.gallery"),h=document.querySelector(".loader"),m=document.querySelector(".load-more-btn"),j=new S(".gallery li a",{captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",nav:!0,captionDelay:250});function g(s){const t=s.map(({largeImageURL:r,webformatURL:a,tags:e,likes:o,views:i,comments:w,downloads:L})=>`<li class="gallery-item">
                <a class="gallery-link" href="${r}">
                  <img class="gallery-image" src="${a}" width='100px' alt="${e.split(",").slice(0,3).join(",")}">
                  <ul class="image-params">
                    <li><b>Likes</b>:<br> ${o}</li>
                    <li><b>Views</b>:<br> ${i}</li>
                    <li><b>Comments</b>:<br> ${w}</li>
                    <li><b>Downloads</b>:<br> ${L}</li>
                  </ul>
                </a>
              </li>`).join("");l.insertAdjacentHTML("beforeend",t),j.refresh()}function C(){l.innerHTML=""}function b(){l.classList.remove("is-shown"),h.classList.add("is-shown")}function c(){h.classList.remove("is-shown"),l.classList.add("is-shown")}function D(){m.classList.add("is-shown")}function u(){m.classList.remove("is-shown")}const d=document.querySelector('[name="search-text"]'),G=document.querySelector(".search-image-btn"),H=document.querySelector(".load-more-btn"),k="Sorry, there are no images matching your search query. Please try again!",A="Please enter your search query image",I="We're sorry, but you've reached the end of search results.";let n=1,y=0;function f(s){q.show({message:s,messageColor:"#ffffff",backgroundColor:"#fe5549",progressBar:!1,position:"center"})}G.addEventListener("click",async s=>{if(s.preventDefault(),d.value.trim()===""){f(A);return}C(),u(),b(),n=1;try{const t=d.value,r=await p(t,n);if(c(),!r.hits||r.hits.length===0){f(k);return}g(r.hits),y=Math.ceil(r.totalHits/15),n<y?D():u()}catch(t){console.log(t),c()}});H.addEventListener("click",async s=>{s.preventDefault(),n+=1,b();try{const t=d.value,r=await p(t,n);c();const e=document.querySelector(".gallery").lastElementChild;if(g(r.hits),e&&e.scrollIntoView({behavior:"smooth",block:"start"}),n>=y){u(),f(I);return}}catch(t){console.log(t),c()}});
//# sourceMappingURL=index.js.map
