import{a as A,S as T,i as g}from"./assets/vendor-BSTwZ_tR.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&i(d)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();const j="https://corsproxy.io/?url=",R="https://pixabay.com/api",B="52704159-1137319808f91d343a45c96fe",F="photo",E="horizontal",x=!0,w=9,C={method:"GET",headers:{Accept:"application/json","Content-Type":"application/json"}};async function q(a,e){try{const r=`${R}/?key=${B}&q=${a}&image_type=${F}&orientation=${E}&safesearch=${x}&page=${e}&per_page=${w}`,i=await A(`${j}${r}`,C);if(!i.data)throw new Error(`HTTP error! Status: ${i.status}`);return i.data}catch(r){throw console.error(r),r}}const b=document.querySelector("ul.gallery"),S=document.querySelector(".loader"),L=document.querySelector(".load-more-btn"),O=new T(".gallery li a",{captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",nav:!0,captionDelay:250});function h(a){const e=a.map(({largeImageURL:r,webformatURL:i,tags:t,likes:s,views:d,comments:M,downloads:v})=>`<li class="gallery-item js-gallery-item">
                <a class="gallery-link" href="${r}">
                  <img class="gallery-image" src="${i}" width='100px' alt="${t.split(",").slice(0,3).join(",")}">
                  <ul class="image-params">
                    <li><b>Likes</b>:<br> ${s}</li>
                    <li><b>Views</b>:<br> ${d}</li>
                    <li><b>Comments</b>:<br> ${M}</li>
                    <li><b>Downloads</b>:<br> ${v}</li>
                  </ul>
                </a>
              </li>`).join("");b.insertAdjacentHTML("beforeend",e),O.refresh()}function D(){b.innerHTML=""}function $(){S.classList.add("is-shown")}function n(){S.classList.remove("is-shown")}function P(){L.classList.add("is-shown")}function p(){L.classList.remove("is-shown")}let l=1,f=0;const o={query:document.querySelector(".js-input-field"),form:document.querySelector(".js-form"),loadMoreButton:document.querySelector(".js-load-more-btn"),gallery:document.querySelector(".js-gallery"),toast:document.querySelectorAll(".iziToast")},c={emptyResponseMessage:"Sorry, there are no images matching your search query. Please try again!",emptyQueryMessage:"Please enter your search query image",endSearchResults:"We're sorry, but you've reached the end of search results."};let y="";function u(a){g.show({message:a,messageColor:"#ffffff",backgroundColor:"#fe5549",progressBar:!1,position:"center",timeout:1e4})}function m(a){g.destroy()}o.form.addEventListener("submit",async a=>{if(a.preventDefault(),l=1,y="",o.toast&&m(),$(),await new Promise(requestAnimationFrame),o.query.value.trim()===""){o.toast&&m(),n(),await new Promise(requestAnimationFrame),u(c.emptyQueryMessage);return}p(),D();try{y=o.query.value.trim();const e=await q(y,l);if(f=Math.ceil(e.totalHits/w),!e.hits||e.hits.length===0){o.toast&&m(o.toast),n(),await new Promise(requestAnimationFrame),u(c.emptyResponseMessage);return}if(!e.hits){const r=document.querySelectorAll(".iziToast");r&&m(r),n(),await new Promise(requestAnimationFrame),u(c.endSearchResults);return}if(l>=f){h(e.hits),n(),u(c.endSearchResults);return}h(e.hits),n(),l<f?P():p()}catch(e){console.log(e),n()}});o.loadMoreButton.addEventListener("click",async a=>{a.preventDefault(),l+=1;try{const e=o.gallery.children.length;p(),$(),await new Promise(requestAnimationFrame);const r=await q(y,l);if(!r.hits||r.hits.length===0){o.toast&&m(o.toast),n(),await new Promise(requestAnimationFrame),u(c.emptyResponseMessage);return}if(!r.hits){o.toast&&m(o.toast),n(),await new Promise(requestAnimationFrame),u(c.endSearchResults);return}if(l>=f){await new Promise(requestAnimationFrame),h(r.hits),n(),u(c.endSearchResults);return}h(r.hits),n(),l<f?P():p();const i=o.gallery.children[e];if(i){const t=i.getBoundingClientRect();console.log(t),window.scrollBy({top:t.height*2,behavior:"smooth"})}}catch(e){console.log(e)}});
//# sourceMappingURL=index.js.map
